CALL def_scalartypes(
  ScalarType('gen', 'Text10', 'VARCHAR(10)'),
  ScalarType('gen', 'Text20', 'VARCHAR(20)'),
  ScalarType('gen', 'Text50', 'VARCHAR(50)'),
  ScalarType('gen', 'Unique', 'UUID'),
  ScalarType('gen', 'Amount', 'DECIMAL(10,2)'),
  ScalarType('gen', 'AnyNum', 'BIGINT')
);

CALL def_compositetypes(
  CompositeType('gen', 'Compo2',
    Scalar(105, 'unique', 'Unique'),
    Scalar(110, 'text10', 'Text10')
  ),
  CompositeType('gen', 'Compo3',
    Scalar(105, 'text20', 'Text20'),
    Scalar(110, 'amount', 'Amount'),
    Scalar(115, 'anynum', 'AnyNum')
  ),
  CompositeType('gen', 'Compo23',
    Inline(105, 'Compo2', prefix => ''),
    Inline(110, 'Compo3', 'co3_'),
    Scalar(115, 'text50', 'Text50')  
  ),
  CompositeType('gen', 'Compo32',
    Scalar(115, 'text50', 'Text50'),
    Composite(110, 'compo3', 'Compo3'),
    Composite(105, 'compo2', 'Compo2')
  )
);


