CALL def_scalartypes(
  ScalarType('gen', 'Text10', 'VARCHAR(10)'),
  ScalarType('gen', 'Text20', 'VARCHAR(20)'),
  ScalarType('gen', 'Text50', 'VARCHAR(50)'),
  ScalarType('gen', 'Unique', 'UUID'),
  ScalarType('gen', 'Amount', 'DECIMAL(10,2)'),
  ScalarType('gen', 'AnyNum', 'BIGINT'),
  ScalarType('gen', 'Date10', 'DATE')
);

CALL def_compositetypes(
  CompositeType('gen', 'Compo2',
    Scalar(105, 'unique', 'Unique', description => 'guid'),
    Scalar(110, 'text10', 'Text10')
  ),
  CompositeType('gen', 'Compo3',
    Scalar(105, 'text20', 'Text20'),
    Scalar(110, 'amount', 'Amount'),
    Scalar(115, 'anynum', 'AnyNum')
  ),
  CompositeType('gen', 'Compo23',
    Inline(105, 'Compo2', prefix => ''),
    Inline(110, 'Compo3', prefix => 'co3_', description => 'inline with prefix'),
    Scalar(115, 'ctext50', 'Text50')  
  ),
  CompositeType('gen', 'Compo32',
    Scalar(115, 'dtext50', 'Text50'),
    Composite(110, 'compo3', 'Compo3'),
    Composite(105, 'compo2', 'Compo2')
  )
);

CALL def_tables(
  GenericTable('gen', 'Table1', 'unique, date10',
    Scalar   (105, 'unique', 'Unique'),
    Scalar   (110, 'date10', 'Date10'),
    Scalar   (115, 'text50', 'Text50'),
    Composite(120, 'compo23', 'Compo23'),
    Inline   (125, 'Compo32', prefix => '')
  ),
  GenericTable('gen', 'Table11', 'anynum',
    Scalar(105, 'anynum', 'AnyNum'),
    RefN  (110, 'Table1')
  ),
  GenericTable('gen', 'Table12', 'anynum',
    Scalar(105, 'anynum', 'AnyNum'),
    RefN  (110, 'Table1', names => 'table1_unique, table1_date10')
  ),
  GenericTable('gen', 'Table13', 'anynum',
    Scalar(105, 'anynum', 'AnyNum'),
    Ref1  (110, 'Table1')
  ),
  GenericTable('gen', 'Table14', 'anynum',
    Scalar(105, 'anynum', 'AnyNum'),
    Ref1  (110, 'Table1', names => 'table1_unique, table1_date10')
  )
);

CALL def_compositetypes(
  CompositeType('nest', 'C3',
    Scalar(105, 's3', 'Text10'),
    Scalar(110, 'q2', 'Text10')
  ),
  CompositeType('nest', 'C2',
    Scalar(105, 's2', 'Text10'),
    Inline(110, 'C3', prefix => 'c3-')
  ),
  CompositeType('nest', 'C1',
    Scalar(105, 's1', 'Text10'),
    Inline(110, 'C2', prefix => 'c2-')
  )
)
