\echo *** SIMPLE DAFAULTS
BEGIN;
CALL def_scalartypes(
  ScalarType('test', 'IntType', 'INT', initial => $INI$123$INI$),
  ScalarType('test', 'TextType', 'TEXT', initial => $INI$'abcde'$INI$)
);
WITH test AS (
SELECT ddlscalartypesdefaults() AS result,
$EXPECTED$ALTER DOMAIN test.IntType SET DEFAULT 123;

ALTER DOMAIN test.TextType SET DEFAULT 'abcde';$EXPECTED$ AS expected)
SELECT result, expected, not equals(result, expected) error FROM test
\gset
\if :error
  \echo '--- RESULT --->'
  \echo :result
  \echo '--- EXPECTED --->'
  \echo :expected
\endif
ROLLBACK;
