\echo *** CREATE FOR SCALAR TYPES
BEGIN;

CALL def_scalartypes(
  ScalarType('test', 'IntType', 'INT'),
  ScalarType('test', 'TextType', 'TEXT')
);

WITH ddl AS (
SELECT ddlcreate() AS result,
'CREATE DOMAIN test.IntType AS INT;
CREATE DOMAIN test.TextType ASx TEXT;' AS expected)
SELECT result, expected, not equals(result, expected) error FROM ddl\gset

\if :error
  \echo '--- RESULT --->'
  \echo :result
  \echo '--- EXPECTED --->'
  \echo :expected
\endif

ROLLBACK;
