\include_relative ../../core/install.psql

\include_relative domain/test.psql


-- ----------------------------------
-- ----------------------------------
-- ----------------------------------
select * from compositetypes;
select * from fields;
select * from scalarfields;
select * from compositefields;
/*
--  config data in code (inserts)
create (enumy puste)
fill config
replace enums
transfer data
primary keys
props
check constraints
refy
unique
indexes
*/